version: "3.8"

services:
  postgres:
    image: postgres:14.5-alpine
    container_name: ada_postgres_teste
    ports:
      - "5435:5432"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=postgres
    volumes:
      - db-ada:/var/lib/postgresql/data

volumes:
  db-ada:
